# SPDX-FileCopyrightText: © 2023 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later

[workspace]
members = [
    "codecs",
    "ffi",
    "test-vectors",
    "urtypes",
    "urtypes/fuzz",
]

[workspace.dependencies]
bech32 = { version = "0.9", default-features = false }
bip39 = { version = "2", default-features = false }
bitcoin = { version = "0.30", default-features = false }
criterion = { version = "0.4" }
foundation-codecs = { path = "codecs" }
foundation-test-vectors = { path = "test-vectors" }
foundation-urtypes = { path = "urtypes" }
heapless = { version = "0.8", git = "https://github.com/japaric/heapless", default-features = false }
hex = "0.4.2"
libfuzzer-sys = "0.4"
minicbor = { version = "0.19.1", features = ["derive"] }
ur = { git = "https://github.com/Foundation-Devices/ur-rs", branch = "dev", default-features = false }
uuid = { version = "1", default-features = false }
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1"

[profile.release]
debug = 1
