# SPDX-FileCopyrightText: © 2023 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Dependencies
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  pass-security-audit:
    name: Pass security audit?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-toolchain
        with:
          toolchain: 1.65
      - run: cargo install --locked cargo-audit
      - run: cargo audit

  are-dependencies-sorted:
    name: Are the dependencies sorted?
    needs: [pass-security-audit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-toolchain
        with:
          toolchain: 1.65
      - run: cargo install --locked cargo-sort
      - run: cargo sort --workspace --check

  are-versions-really-minimal:
    name: Are versions really minimal?
    needs: [pass-security-audit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-toolchain
        with:
          toolchain: nightly
      - run: rustup override set nightly
      - run: cargo check -Z minimal-versions
