# SPDX-FileCopyrightText: © 2023 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Dependencies
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  pass-security-audit:
    name: Pass security audit?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-toolchain
        with:
          toolchain: 1.77
      - run: cargo install --locked cargo-audit
      - run: cargo audit

  are-versions-really-minimal:
    name: Are versions really minimal?
    needs: [pass-security-audit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-toolchain
        with:
          toolchain: nightly
      - run: rustup override set nightly
      # hex-conservative uses wrong minimal versions.
      - run: cargo update -p arrayvec --precise 0.7.4 -Z minimal-versions
      - run: cargo check -Z minimal-versions
